name = "cf-challenge-ai-storycard"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2022-04-05"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "6e312692f2da41498477c592e5f2f3c1"

[[r2_buckets]]
binding = "R2"
bucket_name = "cf-challenge-ai-storycard-prod"

[ai]
binding = "AI"
